version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "isoko-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qv27121x2wo3"
s3_prefix = "isoko-backend"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
