on:
  push:
    branches:
      - master
    # makes it so this job only runs when the backend is changed
    paths:
      - backend/**
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      # sam build 
      - run: |
         cd backend/isoko-backend
         sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: |
         cd backend/isoko-backend
         sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name isoko-backend --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1qv27121x2wo3 --capabilities CAPABILITY_IAM --region us-west-2 
